site :opscode

cookbook 'apt'
cookbook 'apache2'
cookbook 'database'
cookbook 'devbox', git: 'https://github.com/Voronenko/chef-developer_recipes'
cookbook 'java'   
cookbook 'git'   
cookbook 'hostsfile'
cookbook 'php'
cookbook 'mysql'
cookbook 'memcached'
cookbook 'nginx'
cookbook 'nodejs'
cookbook 'npm'
cookbook 'tomcat'
